export const LOCAL_STORE_KEYS = {
  DATA_USER: 'DATA_USER',
  DISPLAY_WEB_FIELDS: 'DISPLAY_WEB_FIELDS',
  DISPLAY_VOUCHER_FIELDS: 'DISPLAY_VOUCHER_FIELDS',
  DISPLAY_CUSTOMER_FIELDS: 'DISPLAY_CUSTOMER_FIELDS',
  DISPLAY_EMPLOYEE_FIELDS: 'DISPLAY_EMPLOYEE_FIELDS',
};
