version: "3.8"
services:
  admin-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: container_sys
    expose:
      - $SERVER_PORT
    ports:
      - $SERVER_PORT:$SERVER_DOCKER_PORT
    env_file:
      - ./.env
    # All variable apply in docker container env
    # Overwrite .env
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=sicnew-db
      - MONGODB_DOCKER_PORT=$MONGODB_DOCKER_PORT
      - URL_CLIENT=http://localhost
    depends_on:
      - mongodb
    # volumes: # Only dev
    #   - ./:/src/app
    #   - /src/app/node_modules
    stdin_open: true
    tty: true

  mongodb:
    image: mongo:latest
    restart: always
    container_name: container_mongo
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    expose:
      - $MONGODB_DOCKER_PORT
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - /mongo-db:/data/db

volumes:
  mongo-db:


